### PR TITLE
Samlaf avs 291 docker compose up does not advance the chain

### LINKED ISSUE #39: docker compose up does not advance the chain
due to some issue with anvil's --load-state restarting the chain at blockNumber 0, when we start anvil, we need to [advance it artificially](https://github.com/Layr-Labs/incredible-squaring-avs/blob/3341d281ce805b27fe19bec7b436cc44feb8b78c/tests/anvil/start-anvil-chain-with-el-and-avs-deployed.sh#L24).

However, the current docker-compose file only starts the chain without doing this, so the aggregator fatals and crashes.

There are 2 ways to fix this:
- hacky way: run a script to advance the chain in the docker-compose file after anvil is up
- proper way: I believe anvil has fixed this bug and now --load-state restarts the chain at the correct block number. Would have to do a bit of investigation (EDIT: not actually fixed.. see https://github.com/foundry-rs/foundry/issues/7502)

### PR DESCRIPTION
**Pull request by samlaf**
Fixes #39 .

### CODE REVIEW

**Comment by wesfloyd** [comment]
Would changing the default batch size help?

image

https://book.getfoundry.sh/reference/cli/forge/script?highlight=batch%20100#forge-script

**Comment by samlaf** [comment]
@wesfloyd this was a separate issue. I linked the issue in the description.
The point here was just to fix the broken docker compose test, since we were merging other PRs with that test failing which is not great practice.

In which context are you recommending using batch here? Not sure I'm following.

**Comment by samlaf** [comment]
Merging because this is needed to unblock other PRs, but we can continue the conversation here or elsewhere @wesfloyd !

**Comment by wesfloyd** [comment]
> @wesfloyd this was a separate issue. I linked the issue in the description. The point here was just to fix the broken docker compose test, since we were merging other PRs with that test failing which is not great practice.
> 
> In which context are you recommending using batch here? Not sure I'm following.

All good, no worries, my misunderstanding.

I thought you were needing to [advance the chain here](https://github.com/Layr-Labs/incredible-squaring-avs/blob/90d3254784d916d519193ad5d64f41063f55b04e/tests/integration/integration_test.go#L234) b/c of the default batch size (100), which could be reconfigured to "1".

However, I'm [learning](https://github.com/foundry-rs/foundry/issues/6679) "some state depends on the block-number at which the interaction happened".

For my understanding/learning purposes - could you share which part of inc squaring is dependent on this "state dependent on block number" limitation? It would help to understand whether this is specific to Inc Sq's design or broadly applicable to all AVS testing.

**Comment by samlaf** [comment]
@wesfloyd this applies to all AVSs.
The main idea is that when we verify signatures, we need to lookup the stake and pubkeys of operators at a certain block.
When an operator registers with an AVS the aggregate pubkey is incremented, and stored for that given block. Hence when we fetch the quorum stake, it looks up the last update block where an operator registered. So if we register all operators with the avs and then stop the chain, when we restart it the chain is at block 0 and so we can't fetch the state. That's one issue but there are others that I'm forgetting right now.

The above logic would be nice to have, instead of needing to register the operator dynamically everytime we restart the chain. There must be another reason why I still need to advance the chain.... but I can't remember right now. Maybe when registering the avs looks at the block number at which an operator registered with eigenlayer? Not sure..

**Pull request merged**
